apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meals-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  # k3s uses local-path provisioner by default
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
